config/routes.rb
Rails.application.routes.draw do
  get "manifest.json" => "progressive#manifest"
  get "offline" => "progressive#offline"
  get "service-worker.js" => "progressive#service_worker"
  root "progressive#start"

  resource :setup, only: [:new, :create, :show], controller: "first_admin"

  devise_for :users, controllers: {
    invitations: "users/invitations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resource :account, only: [:show, :update]
  resource :avatar, only: [:create, :destroy]
  resource :profile, only: [:edit, :update]

  # if Rails.env.development?
  #   mount Lookbook::Engine, at: "/lookbook"
  # end

  authenticated :user, lambda { |u| u.admin? } do
    mount Motor::Admin => "/admin"

    namespace :admin do
      # This currently uses the same namespace as motor-admin.
      # But it seems to work just fine.
      resources :users, only: [:index] do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/binary.rb
class Binary < Thing
  store_accessor :data, :filename
  has_one :byte_array, dependent: :destroy

  validates :filename, :byte_array, presence: true
end

app/models/byte_array.rb
class ByteArray < ApplicationRecord
end

app/models/relation.rb
class Relation < ApplicationRecord
  belongs_to :having, polymorphic: true
  belongs_to :belonging, polymorphic: true
end

app/models/thing.rb
class Thing < ApplicationRecord
  include Discard::Model

  def self.where_json(key, value)
    where("json_extract(data, '$.#{key}') like '#{value}'")
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UserExtras

  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    # :confirmable,
    # :recoverable,
    :rememberable,
    :invitable,
    :validatable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # user.skip_confirmation!      # TODO: if devise confirmable
    end
  end

  def admin?
    id == 1
  end

  store_accessor :data, :first_name, :last_name
  store_accessor :data, :time_zone

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    authorize :application, :account?
  end

  def update
    head :ok # TODO
  end

  private

  def user_params
    params.require(:user).permit(:first_name, last_name)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin!

  def index
    @users = User.where("id > 1").order(:id) # Everyone but admin
  end

  def impersonate
    user = User.find(params[:id])
    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  def require_admin!
    raise unless true_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  impersonates :user

  before_action :redirect_to_admin_create, if: -> { User.count.zero? }
  before_action :authenticate_user!, except: :welcome
  around_action :switch_time_zone, if: :current_user

  protect_from_forgery with: :exception

  rescue_from "Pundit::NotAuthorizedError" do |exception|
    render "not_authorized", status: :unauthorized
  end

  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  private

  def redirect_to_admin_create
    redirect_to new_setup_path
  end

  def render_404
    render "application/404", status: "404"
  end

  def switch_time_zone(&block)
    Time.use_zone(current_user&.time_zone || "UTC", &block)
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < AppController
  # TODO: Add authenticity_token to dynamically created form in imageUpload component
  skip_before_action :verify_authenticity_token, only: :create

  def create
    current_user.avatar.attach(params[:file])
    redirect_to edit_profile_url
  end

  def destroy
    current_user.avatar.purge
    redirect_to edit_profile_url
  end
end

app/controllers/first_admin_controller.rb
class FirstAdminController < ApplicationController
  skip_before_action :redirect_to_admin_create, :authenticate_user!

  before_action do
    redirect_to(root_url) unless User.count.zero?
  end

  def new
    @user = User.new(id: 1)
  end

  def create
    # FIXME: Setting the id here breaks the next user registration as Postgres doesn't increase its id increment.
    # See https://stackoverflow.com/a/37972960/3449673
    @user = User.create(id: 1, confirmed_at: Time.zone.now, **user_params)
    redirect_to new_user_session_path, notice: "Admin user account created."
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
  end

  def update
    current_user.update(profile_params)
    redirect_to edit_profile_url, notice: "Profile updated."
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :time_zone)
  end
end

app/controllers/progressive_controller.rb
class ProgressiveController < ActionController::Base
  protect_from_forgery except: :service_worker

  def manifest
  end

  def offline
  end

  def service_worker
    respond_to do |format|
      format.js
    end
  end

  def start
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  def create
    self.resource = invite_resource
    resource_invited = resource.errors.empty?

    yield resource if block_given?

    if resource_invited
      resource.update(invitation_sent_at: Time.zone.now) # This is required with skip_invitation
      render json: {url: accept_user_invitation_url(invitation_token: resource.raw_invitation_token)}
    else
      respond_with_navigational(resource) { render :new, status: :unprocessable_entity }
    end
  end

  private

  def invite_resource
    # Skip sending emails on invite
    # TODO: Make this configurable
    super { |user| user.skip_invitation = true }
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :github

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "GitHub") if is_navigational_format?
    else
      flash[:error] = "Sorry, something went wrong."
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = "Sorry, something went wrong."
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # To use system time when validating the authenticity token
  skip_around_action :switch_time_zone
end

app/helpers/application_helper.rb
module ApplicationHelper
  def engine_name
    ""
  end

  def confirm_to(text, href, options = {})
    content_tag(:div, {"x-data" => "confirm()", "x-bind" => "root"}) do
      button_to text, href, {"x-bind" => "button", **options}
    end
  end
end

app/views/accounts/_settings.html.erb
<div class="card">
  <h2>Device settings</h2>

  <h3>Notifications</h3>
  <div x-data="notificationRequester" class="flex row">
    <label class="switch" >
      <input type="checkbox" :value="granted" disabled>
      <span class="slider round"></span>
    </label>
    <div x-show="!granted">
      Notifications are disabled.<br>
      <button @click="requestPermission()">Enable notifications</button>
    </div>
    <div x-show="granted">
      Notifications are enabled.<br>
      <button x-bind="test">Show test notification</button>
    </div>
  </div>

  <h3>Push messages</h3>

</div>

app/views/accounts/show.html.haml
- content_for(:title) do
  My account

.container
  %h1
    = yield :title
  .text-muted= current_user.email
  .row
    .col-lg
    .col-lg-4
      .d-grid.gap-2
        - if current_user.admin?
          = link_to "Admin & Analytics", "/admin", class: "btn btn-info"
          = link_to "Impersonate users", "/admin/users", class: "btn btn-warning"
          = link_to "Invite new user", new_user_invitation_url, class: "btn btn-secondary"
        = link_to "Edit profile", edit_profile_url, class: "btn btn-secondary"
        = button_to "Sign out", destroy_user_session_url, method: "delete", class: "btn btn-dark"

app/views/admin/users/index.html.haml
%h1 Impersonate users
%blockquote.blockquote
  %p With great power comes great responsibility.

.card.text-bg-dark
  .card-body
    %table.table-dark.table
      .thead
        %tr
          %th Name
          %th Email
          %th
      .tbody
        - @users.each do |user|
          %tr
            %td= user.full_name
            %td= user.email
            %td.text-end= button_to "Impersonate", impersonate_admin_user_path(user), method: :post, class: "btn btn-sm btn-warning"

app/views/application/404.html.haml
.container.text-center
  %h1(style="font-size: 6rem;") 404
  %h2 Not found
  %a.btn.btn-primary.btn-lg.my-5{href: home_url} Go back

app/views/application/_pretender_info.html.haml
- if current_user != true_user
  .pretender-info
    You are signed in as
    = current_user.email
    = button_to "Back to admin", stop_impersonating_admin_users_path, method: :post, class: "btn btn-sm btn-dark"

app/views/application/_templates.html.haml
%template#confirmModalTemplate
  .modal.fade(aria-hidden="true" aria-labelledby="confirmModalLabel" tabindex="-1" x-data="{}" style="font-size: 1rem;"){"x-on:hidden-bs-modal.dot" => "$el.remove()" }
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-header
          %h5#confirmModalLabel.modal-title Are you sure?
          %button.btn-close(aria-label="Close" data-bs-dismiss="modal" type="button")
        -# .modal-body
        -#   Lorem ipsum dolor sit amet consectetur adipisicing elit.
        .modal-footer
          %button.btn.btn-secondary.js-btn-no(data-bs-dismiss="modal" type="button") Cancel
          %button.btn.btn-primary.js-btn-yes(type="button" x-on:click="$event.target.dispatchEvent(new CustomEvent('confirmed', { bubbles: true }))") Confirm

app/views/application/welcome.html.erb
<section class="centered">
  <header>
    <h1>Welcome to your new application!</h1>

    <p>Follow the steps below to get started.</p>
  </header>

  <%- if User.count.zero? %>
    <p>Create your first user in the console. The first user will be admin.</p>
    <pre><code>User.create(first_name: "Me", email: "me@example.com", password: "123456").confirm</code></pre>
  <%- elsif current_user %>
    <p>Create <code>app/views/app/welcome.html.haml</code> to replace this page's content.</p>
    <p>Afterwards, edit <code>config/routes.rb</code> for custom routes.</p>
    <p><i>Happy hacking!</i></p>
  <%- else %>
    <%= link_to new_user_session_url do %>
      <b>Sign in</b>
    <% end %>
  <% end %>
</section>

app/views/first_admin/new.html.haml
- content_for :title do
  First-time setup

.row
  .col-md
    %h1= yield :title
    %p Let's create your admin account!
  .col-md
    .card
      .card-body
        %h3 Create first admin user
        = bootstrap_form_for @user, url: setup_url do |f|
          = f.text_field :email, required: true, floating: true
          = f.password_field :password, required: true, floating: true, help: "Must be at least 8 characters long"
          = f.primary "Create admin"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) if content_for?(:title) %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel='manifest' href='/manifest.json'>
    <link rel="apple-touch-icon" href="<%= asset_url('app/logo_180.png') %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url('app/logo_16.png') %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url('app/logo_32.png') %>">

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "sprockets" %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="<%= App.config.name %>">
    <meta name="description" content="<%= App.config.description %>">
    <meta name="theme-color" content="<%= App.config.theme_color %>"/>

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= main_app.root_url %>">
    <meta property="og:title" content="<%= yield :title %>">
    <meta property="og:description" content="<%= App.config.description %>">
    <meta property="og:image" content="<%= asset_url('app/logo_large.png') %>">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="<%= main_app.root_url %>">
    <meta property="twitter:title" content="<%= yield :title %>">
    <meta property="twitter:description" content="<%= App.config.description %>">
    <meta property="twitter:image" content="<%= asset_url('app/logo_large.png') %>">

    <%= yield :head %>
  </head>

  <body style="--bs-body-bg: <%= App.config.background_color %>;">
    <%= render "pretender_info" %>
    <%= render "templates" %>
    <%= render template: "layouts/app" %>

    <script type="text/javascript">
      if (navigator.serviceWorker) {
        navigator.serviceWorker.register("/service-worker.js", { scope: "/" })
      }
    </script>
  </body>
</html>

app/views/layouts/preview.html.haml
%html
  = stylesheet_link_tag "application"

= yield

app/views/profiles/edit.html.haml
- content_for(:title) do
  Edit profile

.container-lg
  %h1= yield :title
  .row
    .col-12.col-sm-4.col-lg-3.mb-4
      %div(x-data="imageUpload")
        %div(x-show="!active")
          - if current_user.avatar.attached?
            -# = image_tag current_user.avatar.variant(resize_to_limit: [512, 512]), class: "img-fluid img-thumbnail bg-dark border-dark mb-2"
            = image_tag current_user.avatar, class: "img-fluid img-thumbnail bg-dark border-dark mb-2"
            .btn-group.w-100
              %label.btn.btn-dark.btn-sm(for="avatar-form-input") Change profile picture
              %button.btn.btn-dark.btn-sm.dropdown-toggle.dropdown-toggle-split{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button"}
                %span.visually-hidden Toggle Dropdown
              %ul.dropdown-menu
                %li
                  %a.dropdown-item(data-confirm="Sure you want to delete your profile picture?" data-method="delete" href="/avatar") Delete profile picture
          - else
            .img-fluid.img-thumbnail.bg-dark.border-dark.mb-2.img-initials
              = Initials.svg(current_user.full_name, size: 512, shape: :rect)
            %label.btn.btn-dark.btn-sm.w-100(for="avatar-form-input") Upload profile picture

          = form_with url: "#", class: "text-center" do |f|
            = f.file_field :avatar, "x-bind" => "imageInput", id: "avatar-form-input", class: "d-none"

        %div(x-cloak x-show="active")
          %img.img-fluid(x-ref="preview")

          %button.btn.btn-info(x-bind="uploadButton") Set new profile picture
          %button.btn.btn-secondary{"@click" => "active = false"} Cancel

    .col.col-lg-6
      .card.text-bg-dark
        .card-body
          = bootstrap_form_with model: current_user, url: profile_url, method: :put do |f|
            = f.text_field :first_name, required: true
            = f.text_field :last_name
            = f.time_zone_select :time_zone #, nil, {}, {class: "form-control", "x-data" => "selectComponent"}
            .text-end= f.primary "Save"

app/views/progressive/manifest.json.erb
{
	"dir" : "ltr",
	"lang" : "English",
	"name" : "<%= App.config.name %>",
	"scope" : "<%= main_app.root_path %>",
	"display" : "standalone",
	"start_url" : "<%= main_app.root_url %>",
	"short_name" : "<%= App.config.short_name %>",
	"theme_color" : "<%= App.config.theme_color %>",
	"background_color" : "<%= App.config.background_color %>",
	"description" : "<%= App.config.description %>",
	"orientation" : "any",
	"icons" : [
		{
			"src": "<%= asset_url('app/logo_192.png') %>",
			"type": "image/png",
			"sizes": "192x192"
		},
		{
			"src": "<%= asset_url('app/logo_512.png') %>",
			"type": "image/png",
			"sizes": "512x512"
		}
	],
  "shortcuts": <%= App.config.shortcuts.to_json.html_safe %>,
  "share_target": <%= App.config.share_target.to_json.html_safe %>,
	"url" : "<%= main_app.root_url %>",
	"screenshots" : [],
	"generated" : "true"
}

app/views/progressive/offline.html.erb
<style>
  html, body { height: 100% }

  body {
    background-color: <%= App.config.background_color %>;
    color: <%= App.config.text_color %>;
    display: flex;
    flex-flow: column nowrap;
    align-items: center;
    justify-content: center;
    text-align: center;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
  }
</style>

<h1>Offline</h1>
<p>Check your internet connection.</p>

app/views/progressive/service_worker.js.erb
var CACHE_VERSION = 'v2';
var CACHE_NAME = 'sw-cache-' + CACHE_VERSION;

function onInstall(event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function prefill(cache) {
      return cache.addAll([
        '<%= asset_path 'application.js' %>',
        '<%= asset_path 'application.css' %>',
        '<%= asset_path 'app/logo_192.png' %>',
        '<%= offline_path %>',
        '<%= root_path %>'
      ]);
    })
  );
}

function onActivate(event) {
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames.filter(function(cacheName) {
          // Return true if you want to remove this cache,
          // but remember that caches are shared across the whole origin
          return cacheName !== CACHE_NAME;
        }).map(function(cacheName) {
          return caches.delete(cacheName);
        })
      );
    })
  );
}

function onFetch(event) {
  event.respondWith(
    // try to return untouched request from network first
    fetch(event.request).catch(function() {
      // if it fails, try to return request from the cache
      return caches.match(event.request).then(function(response) {
        if (response) {
          return response;
        }
        // if not found in cache, return default offline content for navigate requests
        if (event.request.mode === 'navigate' ||
          (event.request.method === 'GET' && event.request.headers.get('accept').includes('text/html'))) {
          return caches.match('<%= offline_path %>');
        }
      })
    })
  );
}

self.addEventListener('install', onInstall);
self.addEventListener('activate', onActivate);
self.addEventListener('fetch', onFetch);

app/views/progressive/start.html.erb
<style>
  html, body {
    background-color: <%= App.config.background_color %>;
  }

  .spinner {
    margin: 40vh auto;
    width: 10rem;
    height: 8rem;
    text-align: center;
    font-size: 10px;
  }

  .spinner > div {
    background-color: <%= App.config.theme_color %>;
    height: 100%;
    width: 0.75rem;
    display: inline-block;

    -webkit-animation: sk-stretchdelay 1.2s infinite ease-in-out;
    animation: sk-stretchdelay 1.2s infinite ease-in-out;
  }

  .spinner .rect2 {
    -webkit-animation-delay: -1.1s;
    animation-delay: -1.1s;
  }

  .spinner .rect3 {
    -webkit-animation-delay: -1.0s;
    animation-delay: -1.0s;
  }

  .spinner .rect4 {
    -webkit-animation-delay: -0.9s;
    animation-delay: -0.9s;
  }

  .spinner .rect5 {
    -webkit-animation-delay: -0.8s;
    animation-delay: -0.8s;
  }

  @-webkit-keyframes sk-stretchdelay {
    0%, 40%, 100% { -webkit-transform: scaleY(0.4) }
    20% { -webkit-transform: scaleY(1.0) }
  }

  @keyframes sk-stretchdelay {
    0%, 40%, 100% {
      transform: scaleY(0.4);
      -webkit-transform: scaleY(0.4);
    }  20% {
      transform: scaleY(1.0);
      -webkit-transform: scaleY(1.0);
    }
  }
</style>

<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>

<script>
  window.location = "<%= home_url %>"
</script>

app/views/users/invitations/edit.html.haml
%h2= t "devise.invitations.edit.header"

= bootstrap_form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f|
  -#= render "users/shared/error_messages", resource: resource
  = f.hidden_field :invitation_token, readonly: true

  - if f.object.class.require_password_on_accepting
    = f.password_field :password
    = f.password_field :password_confirmation
    = f.primary t("devise.invitations.edit.submit_button")

app/views/users/invitations/new.html.haml
.container-lg
  .card.text-bg-dark
    .card-body
      %h4.card-title Create invitation

      .row{"x-data" => "{url: null}", "@ajax:success" => "e => e.detail.response.json().then((data) => { url = data.url })"}
        .col
          %p 1. Enter an email address to create a new user account and get a one-time invite link.
          = bootstrap_form_for(resource, as: resource_name, url: invitation_path(resource_name), remote: true, html: { method: :post }) do |f|
            %fieldset(x-bind:disabled="!!url")
              - resource.class.invite_key_fields.each do |field|
                = f.email_field field, required: true, floating: true
                = f.primary "Create invitation token"
        .col
          %template(x-if="!!url")
            %div
              %p 2. Share this link with the new user:
              .border.border-primary.rounded.p-2
                %p.text-secondary.font-monospace(x-text="url")

                %button.btn.btn-primary(x-data="clipboardCopy(url)" x-bind="copyButton")
                  = inline_svg_tag 'icons/clipboard.svg'
                  Copy to clipboard